#!/usr/bin/env bash
#
# Generate a gitignored Helm values file with random secrets for LOCAL/DEV
# installs (secrets.create=true). For Talos/GitOps, secrets come from Vault
# instead and this script is not used.
#
# Usage:
#   ./scripts/gen-secret-values.sh            # writes values-secret.local.yaml
#   ./scripts/gen-secret-values.sh --force    # overwrite an existing one
#
# Then:
#   helm install bap . -f values-local.yaml -f values-secret.local.yaml -n basic-ai-platform --create-namespace
#
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="values-secret.local.yaml"

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1
if [ -f "$OUT" ] && [ "$FORCE" -ne 1 ]; then
  echo "ERROR: $OUT already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

secret() { openssl rand -base64 "${1:-32}" | tr -d '\n/+=' | cut -c1-"${2:-40}"; }
hex()    { openssl rand -hex "${1:-32}"; }

umask 077
cat > "$OUT" <<EOF
# Generated by scripts/gen-secret-values.sh — random secrets, DO NOT COMMIT.
secrets:
  create: true
  values:
    postgresPassword: "$(secret 32 40)"
    litellmMasterKey: "sk-$(secret 32 40)"
    litellmSaltKey: "$(hex 32)"
    webuiSecretKey: "$(hex 32)"
    grafanaPassword: "$(secret 24 32)"
EOF

echo "Wrote $OUT (mode 600). Pass it after values-local.yaml on helm install."
