#!/usr/bin/env bash
#
# Generate a .env for the Basic AI Platform compose stack.
#
# Secrets (passwords, keys, salts) are randomized on each run. The two
# connectivity values that must point at your real model server —
# AI_SERVER_IP and LOCAL_AI_BASE_URL — default to the host referenced in
# litellm/config.yaml and can be overridden from the environment:
#
#   AI_SERVER_IP=192.168.1.50 ./scripts/gen-env.sh
#   LOCAL_AI_BASE_URL=http://host:8000/v1 ./scripts/gen-env.sh
#
# Usage:
#   ./scripts/gen-env.sh            # write .env (refuses to clobber an existing one)
#   ./scripts/gen-env.sh --force    # overwrite an existing .env
#
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env"

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  echo "ERROR: $ENV_FILE already exists. Re-run with --force to overwrite it." >&2
  exit 1
fi

# --- helpers -------------------------------------------------------------
# URL-safe secret: base64 then strip chars that are awkward in URLs/DSNs.
secret() { openssl rand -base64 "${1:-32}" | tr -d '\n/+=' | cut -c1-"${2:-40}"; }
hex()    { openssl rand -hex "${1:-32}"; }

# --- non-secret / connectivity values (override via env) -----------------
AI_SERVER_IP="${AI_SERVER_IP:-10.6.6.13}"
LOCAL_AI_BASE_URL="${LOCAL_AI_BASE_URL:-http://${AI_SERVER_IP}:11434/v1}"
LOCAL_AI_API_KEY="${LOCAL_AI_API_KEY:-none}"
POSTGRES_USER="${POSTGRES_USER:-aiplat}"
POSTGRES_DB="${POSTGRES_DB:-aiplat}"
GRAFANA_USER="${GRAFANA_USER:-admin}"

# --- secrets (fresh each run) --------------------------------------------
POSTGRES_PASSWORD="$(secret 32 40)"
LITELLM_MASTER_KEY="sk-$(secret 32 40)"
LITELLM_SALT_KEY="$(hex 32)"
WEBUI_SECRET_KEY="$(hex 32)"
GRAFANA_PASSWORD="$(secret 24 32)"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/gen-env.sh — secrets are random; do not commit this file.
# Connectivity values point at your local model server; edit if they are wrong.

# --- Postgres (keys/logs/embeddings) ---
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

# --- LiteLLM gateway ---
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
LITELLM_SALT_KEY=${LITELLM_SALT_KEY}

# --- Local AI model server (the "Bedrock equivalent") ---
LOCAL_AI_BASE_URL=${LOCAL_AI_BASE_URL}
LOCAL_AI_API_KEY=${LOCAL_AI_API_KEY}

# --- Open WebUI ---
WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}

# --- Prometheus (resolves "ai-server" to the real host) ---
AI_SERVER_IP=${AI_SERVER_IP}

# --- Grafana ---
GRAFANA_USER=${GRAFANA_USER}
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}
EOF

echo "Wrote $ENV_FILE (mode $(stat -f '%Lp' "$ENV_FILE" 2>/dev/null || echo 600))."
echo "  AI_SERVER_IP=${AI_SERVER_IP}"
echo "  LOCAL_AI_BASE_URL=${LOCAL_AI_BASE_URL}"
echo "Verify those match your model server, then:  docker compose up -d"
